name: Deployment
run-name: ${{ github.actor }} started the deployment
on:
  release:
    types:
    - created
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
